### ISSUE TITLE
Define px values (except fontSizeNormal) as rems

### ISSUE THREAD

**Issue by adamyeats** [appsignal/design-language#15]
Here's something nice we can do with our typography scale: `fontSizeNormal` should equal the base font size of the `html` element, and all other sizes should be in `rem`s (a scaled value of `fontSizeNormal`).

Here's an online tool for converting `px` to `rem`s. I have hardcoded these values into the `.c-button` component for now.

**Comment by wesoudshoorn** [comment]
This was fixed in #16
