### ISSUE TITLE
Link colors with variables?

### ISSUE THREAD

**Issue by wesoudshoorn** [appsignal/design-language#50]
Brainfart:

Something that happens quite often in design when you're switching from light to dark backgrounds is that you'll have to redefine link styles. It's easy to let elements inherit a text color with `.u-bg-grey-darkest` and `.u-text-white`, but the colors of links and hover states would be annoying to always have to add `.u-link-white` or something like that.

If we create a system where link colors are defined with `--var-link-color` and `--var-link-color-hover`, we can create a utility class with something like `.u-links-white` that resets the variables for the scope of that element.

**Comment by jvanbaarsen** [comment]
@wesoudshoorn One thing that I was thinking about is to generate `hover` variants of the text colors. So you get `.hover:u-t-white` for example. That way we can also use if for things that are not actually links.

**Comment by jvanbaarsen** [comment]
@wesoudshoorn Maybe we can try and make a decision on this before my holiday?
